M48
; DRILL file KiCad 10.0.6 date 2026-09-04T23:48:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-04T23:48:06+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X128.688Y-85.5
T2
X116.5Y-89.235
X116.5Y-91.775
X135.0Y-89.25
X135.0Y-91.79
M30
